name: GNNenv
channels:
  - conda-forge       
  - defaults
dependencies:
  - python=3.10
  - mamba
  - xtb
  - xyz2mol
  - cmake
  - pip:
      - --find-links https://data.pyg.org/whl/torch-2.5.1+cu124.html
      - --extra-index-url https://download.pytorch.org/whl/cu124

      - torch==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - torchaudio==2.5.1+cu124
      
      - pyg_lib
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv
      - molvoxel
      - lightning
      - git+https://github.com/maurerv/pyzernike
      - e3fp
      - psutil
      - pandas
      - scikit-learn
      - mdanalysis
      - prolif
      - biopython
      - py3dmol
      - pyyaml
      - optax
      - jax
      - scipy
      - numpy
      - open3d
      - umap-learn
      - plotly
      - rdkit
      - torch_geometric
      - tensorboard
